### ISSUE TITLE
GOBI - EBSCO downloader

### ISSUE THREAD

**Issue by masteoo** [C0D3D3V/Ebsco-Downloader#1]
Hello, sorry, first of all thanks for this tool. 
Do you think is possible to download epub from www.gobi3.com? 
In private I can give you Gobi credentials if you wanna try.
This is a ebook link: 
https://web.p.ebscohost.com/ehost/ebookviewer/ebook?sid=80683e47-488b-4c26-a657-098712cbac7c%40redis&vid=0&format=EK

Thanks again

**Comment by C0D3D3V** [comment]
You are welcome ❤️
