### ISSUE TITLE
epub - error if opening with softwares like sumatra or aquile

### ISSUE THREAD

**Issue by sefirothmorpheus** [C0D3D3V/Ebsco-Downloader#2]
hello
why am i not able to open the epub created by this tool with softwares like sumatra or aquile?
calibre reads the file, but i do not like calibre as an epub reader, aquile is much better.

![image](https://github.com/C0D3D3V/Ebsco-Downloader/assets/156643499/c40c3863-2500-46c9-a91a-4f6b6e9c349c)
error on sumatra

![image](https://github.com/C0D3D3V/Ebsco-Downloader/assets/156643499/8ba796d0-c423-4fc7-b9bf-615a76803ca4)
error on aquile

just to be clear: i do not receiev such error from sumatra/aquile on all other epubs i have, only on those created by your tool

can you please have a look at this issue?
thanks

**Comment by C0D3D3V** [comment]
Please test the latest version. If it still does not work, open a new issue.
