### ISSUE TITLE
epub - unreadable on sumatra/aquile

### ISSUE THREAD

**Issue by sefirothmorpheus** [C0D3D3V/Ebsco-Downloader#3]
problem not yet solved. still books cannot be opened with softwares like sumatra/aquile

**Comment by C0D3D3V** [comment]
![grafik](https://github.com/C0D3D3V/Ebsco-Downloader/assets/14315968/1922ff63-1a80-410f-a2f9-43d74e701ea6)

For me it is working. Wasted a lot time to get Windows running. I can not help you if you give me not more information.

**Comment by C0D3D3V** [comment]
update your reader, your sumatra is outdated.
Check that ebso-dl is on latest version, use:
`ebsco-dl --version`.

0.3.6 is latest version

**Comment by sefirothmorpheus** [comment]
i have:
1) downlaoded and installed again sumatra (3.5.2 64)
2) downloaded and installed again aquile (1.1.37)
3) downloaded the new code few seconds ago
4) recreated the epub "tire de letra"
and these are the outcomes:

![image](https://github.com/C0D3D3V/Ebsco-Downloader/assets/156643499/ceabb9d5-c6b0-42e5-9b16-0cfa83947a03)

![image](https://github.com/C0D3D3V/Ebsco-Downloader/assets/156643499/768e884b-1b02-48a7-890e-5114dd733211)

i use windows 10.
which other info you require?

also, using calibre, i have noticed that with files created by your tools, it is not possible to convert them to pdf... while, i do not have any problem converting all other epubs downloaded from other websites/tools.

**Comment by C0D3D3V** [comment]
Converting to pdf works and also I now tested aquile:
![grafik](https://github.com/C0D3D3V/Ebsco-Downloader/assets/14315968/46257fc9-957f-4ecd-a75a-bc5bbcc62ad8)

Tell me the output of: `ebsco-dl --version`

**Comment by sefirothmorpheus** [comment]
0.3.6
![image](https://github.com/C0D3D3V/Ebsco-Downloader/assets/156643499/7b2aa9a7-c59f-4f97-8791-1f8cb8d24400)

**Comment by sefirothmorpheus** [comment]
0.3.6
![image](https://github.com/C0D3D3V/Ebsco-Downloader/assets/156643499/68c8e9ee-f42c-4744-bf44-62973c40a278)

**Comment by C0D3D3V** [comment]
Should be fixed now. I hope you love it. 
Next time use linux!
