### ISSUE TITLE
PDF download issues

### ISSUE THREAD

**Issue by rainrdx** [C0D3D3V/Ebsco-Downloader#4]
Hi,

Thank you so much for maintaining this and recently adding PDF support. I recently tried a book, and seems all PDF files are 403 byte files. And the files say

<script type="text/javascript">
	if (window.parent.jQuery('#ePubFrame').length != 0) {
		window.parent.jQuery('#ePubFrame').trigger('pageError', '/ehost/detail?sid=[redacted]&vid=0');
	} else if (window.parent.jQuery('#viewport').length != 0) {
		window.parent.jQuery('#viewport').trigger('pageError', '/ehost/detail?sid=[redacted]&vid=0');
	}
</script>

**Comment by C0D3D3V** [comment]
contact me via mail, send me the book name and a link to it. I do not have myself access to ebsco, ...

**Comment by C0D3D3V** [comment]
you can update and test the new version

**Comment by VINTX2** [comment]
Same issue here.
I am using the latest version (0.4.1).

**Comment by C0D3D3V** [comment]
@VINTX2 I can fix it if you provide me an account via mail. I guess your EBSCO instance is using the viewer API v2. I have no access to such an EBSCO instance.
