### ISSUE TITLE
you able to create a tool which can download books in preview from hoepli?

### ISSUE THREAD

**Issue by sefirothmorpheus** [C0D3D3V/Ebsco-Downloader#5]
for example, these two:

https://copertine.hoepli.it/hoepliscuola/Camagni,-Informatica-e-Applicazioni-vol.-4---Hoepli/index.html

https://copertine.hoepli.it/hoepliscuola/1548-Lughezzani_Clippy_Cloud_Plus_Programmazione/index.html

**Comment by C0D3D3V** [comment]
I think I can do that. But it's time-consuming because it's not trivial. Get in touch by email if you're interested.
