### ISSUE TITLE
error on a book (Il mio MBA personale : I segreti del business per far decollare la carriera)

### ISSUE THREAD

**Issue by sefirothmorpheus** [C0D3D3V/Ebsco-Downloader#7]
![ebsco](https://github.com/C0D3D3V/Ebsco-Downloader/assets/156643499/62af4e1b-da56-4ff4-b5c3-9d7eafe5f520)

on other ebooks, so far, i do not have any problem, only on this specific one

**Comment by C0D3D3V** [comment]
thanks for the report❤️ ️

**Comment by C0D3D3V** [comment]
should be fixed in the new version
