### ISSUE TITLE
no images in some EPUBs

### ISSUE THREAD

**Issue by stefan5588** [C0D3D3V/Ebsco-Downloader#8]
Greetings! The tool works great, however some epubs have missing images, due to the different location of these images. For ex.,, in Quality Hollywood: Markers of Distinction in Contemporary Studio Film (2016), the correct path for images is OEBPS/html/images/, while the tool looks only in OEBPS/images/ and finds nothing.

**Comment by C0D3D3V** [comment]
Uff, this bug is already in there since my last update. It should have worked before my changes.
That's the problem if you have no tests, have a small user base and do not use the program yourself :D

I will make a fix :)

**Comment by C0D3D3V** [comment]
Should be fixed in the new version. Thank you very much!

**Comment by stefan5588** [comment]
Thank YOU! ❤️
